version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    working_directory: ~/twitter-feed-function
    steps:
      - checkout
      - run: echo "$TWITTER_API_CREDENTIALS_JSON" > twitter-api-credentials.json
      - run: echo "$GOOGLE_AUTH" | base64 -i --decode > "$HOME/gcp-key.json"
      - run: gcloud auth activate-service-account --key-file "$HOME/gcp-key.json"
      - run: gcloud --quiet config set project "$GOOGLE_PROJECT_ID"
      - run: gcloud beta functions deploy search --stage-bucket "$GOOGLE_PROJECT_ID" --trigger-http
